name: 🐛 Design Bug Report - Version 2
description: Create a report to help us improve
labels: [🐛 bug, version2]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Feedback by the community has a very high value for us, to improve our work and to have every other user benefit from it as well. 🙂
        |
        Please make sure that you are using the latest version of the tool. Especially in Sketch, the use of an older version can lead to errors in the components that no longer occur in the current version.

  - type: checkboxes
    id: ds-library
    attributes:
      label: Which design system content is impacted? * (PLEASE SELECT THE LIBRARY)
      description: Select all the ones that apply, to the best of your knowledge.
      options:
        - label: Sketch Web Anwendungen
        - label: Sketch Android & iOS
        - label: Sketch Illustrative Icons
        - label: Sketch Funktionale Icons
    validations:
      required: true

  - type: input
    id: ds-version
    attributes:
      label: Which version is impacted?
      description: Please let us know which version number is affected.
      placeholder: ex. 2.3.15
    validations:
      required: false
      
  - type: textarea
    id: reproduction_fiddle
    attributes:
      description: A clear and concise description of what the bug is.
      label: Reproduction case
      placeholder: How can we reproduce the error?
    validations:
      required: true

  - type: textarea
    id: expected_behaviour
    attributes:
      description: A clear and concise description of what you expected to happen.
      label: Expected Behaviour
      placeholder: What did you expect to see?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      description: If applicable, add screenshots to help explain your problem.
      label: Screenshots
      placeholder: Screenshots often help us to better understand the problem.

  - type: textarea
    id: additional_information
    attributes:
      label: Add any other context about the problem here.
    validations:
      required: false
